osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - master
before_deploy:
- mkdir $TRAVIS_BUILD_DIR/release
- cp $TRAVIS_BUILD_DIR/build/*.zip $TRAVIS_BUILD_DIR/release/
- cp $TRAVIS_BUILD_DIR/build/*.dmg $TRAVIS_BUILD_DIR/release/
deploy:
  provider: releases
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: Mm6dACoV9REqenDLqnK+HnEEGa+LDYpoT3GWLgMVSoKuII79a9nERDZNXN2qofBABmQHqicTGfjZfdBjK3lqmi7yQoEwuJVlWTdfuG6CHu0PBKPUXeEtjb3guYeimRXkq3OCxgI/Qx8yoR6eEutYVO5VPCzTiB9oT55SOGWYIvkkuDI6/abf+VYCxDPvix7f0ka+h92mXXEmYQoP8DWzFehPrqeRiORIIWiK1ibNPbc7c4Y4zkM654HNRnrxbm44dDRwJmo4G7uG3rod+bPubIBK/4DoO4dCyMWgjPwmEkplRl70iG/tR10xIAaKBsSUXS0NtTLd8xfURfBHb5kCXt1wWZd7mKPfQSUGNutJZvjZrFjvd6bNpKkQRlvOeH4F1vNbK7ugn4OMjBtaAJq642Zypuq22NjevfgefwcZGv90MTYoBANiF27HftEbYaxLXAgpJmj9OW1YU3+UF/GIVylAJAdm7c+EVvfgsJH1VkpfTfdXRXjACubaTRhrYUt5REXSQo2rgX0Q90sjnEsEbTClQiQkEsEsv1UAV9r8gKVdiixu9AenFLjan9LRw3Z4egD/Dsd4zdfUDNnRtQ7ohv9ZZzctKQakjos4FOeO6jL1dydfA5AuFkfml8RRrkC9c4i2R81mkd4v3IXFtAintaw+317HILti/gKEeMDQPF0=
