osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - master
env:
  global:
    secure: YCQoaRkxisbd/jOa5UoROq7XioIyq4F/7AfuiaElG6mHyScKmM+TO3Hdr3jUyImRoqbzHXvj0Lcuelwph7FNQ+ffowxzuq/1MWSxzdQ9ubkkEis++5IlulLPuh/PYRxM75cvt+b8ZoEunTT9a3rzmQ0v133V6S1NLpFyhkU+0eptNW6/mMzrmN5qLSOsUqddP96Uhfpy7MVrXctuomfuXYCVCSeoaju6Oaw7x73iBfKuqY7ABhzkwKkH8FzXqudEr9G3whEBExSHIGAMy+Y6/FPZMjIrG7SNojA2CDblOS2+lcTP66xUuyiCuAuciqD55qOYQ5yPSAb5YRnwKRom9q29MtwwLn3KuR1xujxC3fhunCF3TzdUbVpa59W2weYXN5y4VHH0dzuLqdoDh/hNlgwCBpVW8mSpeIXtATE4VoYhCIgOsJXjccaygh6LUVRhR2cF/5wRpIsfa+rOvVDFWfWvpYOG8blMYnhsngK73J4EsllU0THfDdzj3vbqDRG6ignLBGUzc9dRDbX3bhLLO+ddNv0c3Be91HcRSeCS4zQV338KCxOi+oY55CQxUevPkwkQnQD/5I9BKiKR9iHPXM47bvgP9YGFfy+7msSlOYqnPwbFlua4hO0D4GoRkPu/70/6lRDriee4BPXZ4X2fTzTEZHJN7hEa5+Ib9d36hLE=
